### ISSUE TITLE
Building without nix

### ISSUE THREAD

**Issue by rapha8l** [RGBCube/crash#1]
Hi,

Is there a way to build it without nix ? I can't change the default fallbackshell and so it fails to build
thanks

**Comment by RGBCube** [comment]
Oh, I should probably add a note in the readme. Will do when I get on my laptop, but here's the command you need: `zig build --release=safe --cpu=baseline -Dfallback_shell=<path>`

Requires Zig 0.12.0, might work on master also

**Comment by rapha8l** [comment]
thanks !

**Comment by rapha8l** [comment]
For you information 
```
zig build --release=safe --cpu=baseline -Dfallback_shell=/bin/bash
unrecognized argument: '--cpu=baseline'
```

without cpu=baseline, it builds !

**Comment by RGBCube** [comment]
Oh, it seems to be `-Dcpu=baseline`. Added that to the readme, this makes the issue resolved

**Comment by rapha8l** [comment]
thanks again
