### ISSUE TITLE
Shell env setting

### ISSUE THREAD

**Issue by rapha8l** [RGBCube/crash#2]
Hi,
it's me again ;)
I'm not sure on how to set in a correct way the shells env, can you elaborate a bit more on this ?
Thanks

**Comment by RGBCube** [comment]
You will need to make PAM set the environment variable early on in the boot process, in NixOS this is handled by the option `environment.sessionVariables`, what distro are you using?

**Comment by rapha8l** [comment]
arch for the moment
thanks for helping

**Comment by rapha8l** [comment]
ok it seems it's in /etc/environment

**Comment by rapha8l** [comment]
also /etc/security/pam_env.conf

**Comment by RGBCube** [comment]
Closing this as resolved :)
